# Copyright 2021 Hewlett Packard Enterprise Development LP

global:
  authGateways:
  - services/services-gateway
  - services/customer-admin-gateway

image:
  repository: artifactory.algol60.net/csm-docker/stable/quay.io/sighup/gatekeeper-policy-manager
  tag: v0.4.0
  pullPolicy: IfNotPresent

gatekeeper-policy-manager:
  ingress:
    enabled: true
  # Configure external hostname for Istio ingress
  externalAuthority: oa-gpm.local
  externalUrl: https://opa-gpm.local
